global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    cluster: "kubernetes"

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['127.0.0.1:9090']
    labels:
      instance: prometheus

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["http://192.168.2.11:30903"]

rule_files:
- /etc/prometheus/*-rule.yml
